apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole
  namespace: flux-system
data:
  values.yaml: |
    podDnsConfig:
      enabled: true
      policy: None
      nameservers:
        - 1.1.1.1
    ingress:
      enabled: true
      path: /pihole
      hosts:
        - raspi.router.lan