---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: flux-system
spec:
  targetNamespace: pihole
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
      version: '0.14.7'
  interval: 1m0s
  valuesFrom:
  - kind: ConfigMap
    name: pihole
