---
- name: Generate node hash based on IP
  shell: echo "$(curl icanhazip.com)" | md5sum | head -c 12
  register: node_hash

- debug:
    msg: "node name: worker.{{ node_hash.stdout }}"

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-agent.service"
    owner: root
    group: root
    mode: 0644

- name: Copy K3s env file
  template:
    src: "k3s.service.env.j2"
    dest: "{{ systemd_dir }}/k3s-agent.service.env"
    owner: root
    group: root
    mode: 0644

- name: Enable and check K3s service
  systemd:
    name: k3s-agent
    enabled: yes
    daemon_reload: yes
    state: restarted