---
# Install tailscale
- name: Tailscale auth key is required
  fail:
    msg: >
      Must include tailscale_auth_key in group vars
  when: tailscale_auth_key is not defined

- name: Add tailscale package signing key
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/focal.noarmor.gpg
    keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg

- name: Add tailscale repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu focal main
    filename: tailscale
    state: present

- name: Install tailscale
  apt:
    name: tailscale
    state: latest
    update_cache: yes

# Run tailscale
- name: Start tailscale
  shell: sudo tailscale up --reset --auth-key {{ tailscale_auth_key }}

- name: Ensure tailscale connection is active
  shell: >
    if [ "$(tailscale status --peers=false --active | wc -l)" -eq "1" ]; then
      exit 0
    else
      exit 1
    fi

# Prep variables for use
- name: Get tailscale ip to broadcast
  shell: tailscale ip -4
  register: tailscale_ip

- name: Set node ip fact
  set_fact:
    node_ip: "{{ tailscale_ip.stdout }}"
