---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argo
spec:
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argo-helm
        namespace: flux-system
      version: '4.9.16'
  interval: 1m0s
  valuesFrom:
  - kind: ConfigMap
    name: argo
    valuesKey: values.argocd.yaml