helmOperator:
  create: false
git:
  url: "git@github.com:mchum/homecluster.git"
  branch: main
  path: infra/platform-apps
image:
  repository: raspbernetes/flux
  tag: 1.21.0
registry:
  rps: 1
  burst: 1
memcached:
  enabled: true
syncGarbageCollection:
  enabled: true
  dry: false