apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium
  namespace: kube-system
data:
  values.yaml: |
    crds:
      enabled: true
    operator:
      replicas: 1
    ingressController:
      enabled: true
      loadBalancerMode: shared
    gatewayAPI:
      enabled: true