apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium
  namespace: kube-system
data:
  values.yaml: |
    crds:
      enabled: true
    kubeProxyReplacement: true
    nodeIPAM:
      enabled: true
    envoy:
      image:
        repository: mattcwc/cilium-envoy-gperftools
        digest: sha256:d6cb0c8129e6a1d947cc87214fbb90671d24cf9f5f57c746c1cd4ddbbef526aa
    operator:
      replicas: 1