apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium
  namespace: flux-system
data:
  values.yaml: |
    crds:
      enabled: true
    kubeProxyReplacement: false
    k8sServiceHost: raspi.router.lan
    egressMasqueradeInterfaces: eth0
    hostPort:
      enabled: true
    hostServices:
      enabled: true
    bgp:
      enabled: false
    bgpControlPlane:
      enabled: false
    nodeIPAM:
      enabled: true
    operator:
      replicas: 1
    ingressController:
      enabled: true
      loadBalancerMode: shared
    gatewayAPI:
      enabled: true
    nodeInit:
      enabled: true