apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium
  namespace: flux-system
data:
  values.yaml: |
    crds:
      enabled: true
    kubeProxyReplacement: true
    nodeIPAM:
      enabled: true
    envoy:
      image:
        repository: mattcwc/cilium-envoy-gperftools
    operator:
      replicas: 1