---
- hosts: cluster
  gather_facts: yes 
  become: yes
  roles:
    - role: k3s/download
    # - role: tailscale
    # - role: flannel/download

- hosts: controlplane
  become: yes
  roles:
    - role: k3s/controlplane

# - hosts: workernode
#   become: yes
#   roles:
#     - role: k3s/worker