---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: '1.9.0'
  targetNamespace: cert-manager
  interval: 1m0s
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager
