---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  targetNamespace: metallb-system
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      version: '0.14.7'
  interval: 1m0s
  valuesFrom:
  - kind: ConfigMap
    name: metallb
