---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: flux-system
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  replicas: 1
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: "true"